<?php
return [
    '1' => [
        'country' => 'DE',
        'topic' => 'Rentenpunkte',
        'descr' => 'Die Rentenpunkte sind unfair berechnet.',
        'is' => 'Für ca. €3500 Gehalt im Monat erhält man zur Zeit einen Rentenpunkt.',
        'problem' => 'Für den Mindestlohn erhält man lediglich ca. 0,3 Rentenpunkte im Jahr. Die Schere zwischen Arm und Reich wird immer breiter. Arbeit lohnt sich nicht.',
        'gov' => 'Die Regierung will die Rente ein wenig erhöhen',
        'error' => 'Dies erzeugt hohe Kosten, aber nur bei den Menschen, die bereits eine gute Rente erhalten.',
        'we' => 'Rentenpunkte sollten nach Arbeitszeit bemessen werden.',
        'goal' => 'Fleißige Menschen werden belohnt. Ansporn und Zufriedenheit.',
        'disc' => [
            'Mona' => 'Was ist mit Hausfrauen?',
            'gizmore' => 'Gute Frage!',
        ],
        'voting' => '1',
        'petition' => null,
    ],
    '2' => [
        'country' => 'DE',
        'topic' => 'Direkte Demokratie',
        'descr' => 'Wir wollen Volksabstimmungen in Deutschland einführen, oder sogar direkte Demokratie.',
        'is' => 'Zur Zeit Stimmen Abgeordnete über Gesetze und Regelungen ab. Diese wählen meist das, was die Partei vorgibt.',
        'problem' => 'Es kommt oft Unsinn heraus. Das Volk wird nicht gefragt, und die vorgeschlagenen Regeln sind ein schlechter Kompromiss von der Koalitionsregierung.',
        'gov' => '',
        'error' => '',
        'we' => 'Wir wollen Volksabstimmungen. Der E-Perso kann für Elektronische Abstimmungen eingesetzt werden, zusätzlich zu altmodischen Wahlverfahren. Nicht jeder soll Wahlberechtigt sein. Vorraussetzung ist fünfjährige deutsche Staatsbürgerschaft, ein Schulabschluss sowie ein leeres Vorstrafenregister.',
        'goal' => 'Das Volk soll mitbestimmen dürfen.',
        'disc' => [
        ],
        'voting' => '0',
        'petition' => '2023-06-07 13:37:42.666',
        'pet_url' => 'https://www.change.org/p/direkte-demokratie-f%C3%BCr-deutschland',
    ],
    '4' => [
        'country' => 'DE',
        'topic' => 'Deutschlandticket',
        'descr' => 'Das Deutschlandticket ist schlecht umgesetzt und Diskriminierend.',
        'is' => 'Das Ticket kann nur Online bestellt werden, ein Smartphone ist anscheinend Pflicht, genauso wie ein fester Wohnsitz und ein immer gedecktes Konto.',
        'problem' => 'Die Hürde beim Bestellen ist enorm. Obdachlose und Menschen ohne Handy sind aussen vor. Barrierefrei ist es wohl auch nicht so.',
        'gov' => '',
        'error' => '',
        'we' => 'Das Deutschlandticket sollte auch Bar, ohne Abbo, erhältlich sein.',
        'goal' => 'Dies erzeugt günstigen Transport für mehr Bürger.',
        'disc' => [
        ],
        'voting' => '0',
        'petition' => null,
    ],
    '5' => [
        'country' => 'DE',
        'topic' => 'Wärmepumpen',
        'descr' => 'Der Zwang zu Wärmepumpen ist unsinnig.',
        'is' => 'Wärmepumpen sind kaum im Einsatz. Viele Haushalte verfügen über gute Gas- oder Ölheizung, diese sind aber Klimaschädlich',
        'problem' => 'Wärmepumpen sind CO2-Neutral, aber nur wenn die Energiewende funktioniert.',
        'gov' => 'Man will andere Heizungen verbieten und nur Wärmepumpen erlauben.',
        'error' => 'Wärmepumpen sind im Winter ineffizient, gerade dann, wenn Solarenergie wenig verfügbar ist. Hohe Kosten werden auf die Bürger abgewälzt. Strom ist ebenfalls sehr teuer.',
        'we' => 'Alte Heizungen sollten nicht verboten werden. Wärmepumpen könnten staatlich gefördert werden.',
        'goal' => 'Die alte Heizversorgung soll erhalten bleiben, und Bürgerfreundlich gehandelt werden.',
        'disc' => [
            'gizmore' => 'Ich glaube das ist bereits wieder vom Tisch. Case closed?',
        ],
        'voting' => '0',
        'petition' => null,
    ],
    '6' => [
        'country' => 'DE',
        'topic' => 'Cannabis',
        'descr' => 'Das neue Cannabis-Gesetz ist widersprüchlich und nicht gut durchdacht.',
        'is' => 'Die Bundesländer geben eine geringe Menge vor, deren Besitz meist nicht zur Strafverfolgung führt. Der Anbau und Verkauf sind strafbar.',
        'problem' => 'Als Konsument fühlt man sich oftmals wie ein Verbrecher. Als Verkäufer oder Züchter ist man einer. Das Cannabis vom Schwarzmarkt ist oftmals gestreckt oder mit Dünger verunreinigt.',
        'gov' => 'Die Regierung will nun eine etwas höhere geringe Menge im Besitz erlauben. Der private Anbau ist erlaubt. Die Abgabe soll über Vereine erfolgen.',
        'error' => 'Die Qualität ist weiterhin nicht gesichert. Es gibt kaum Steuereinnahmen.',
        'we' => 'Wir schlagen die kontrollierte Abgabe in Apotheken ab 21 Jahren vor. Preisvorstellung: €20/g. Abgabe nur gegen Personalausweis, um bessere Kontrollen zu ermöglichen. Die Infrastruktur besteht bereits. Der Privatanbau könnte weiterhin illegal bleiben um die Kontrolle zu gewährleisten.',
        'goal' => 'Damit wollen wir die Qualität sichern, die Beschaffung erleichtern und hohe Steuereinnahmen generieren. Die Abgabe',
        'disc' => [
            'gizmore' => 'Wie hoch ist die geringe Menge als Züchter?'
        ],
        'voting' => '1',
        'petition' => null,
    ],

    '47' => [
        'country' => 'DE',
        'topic' => 'Kindergeld',
        'descr' => 'Das Kindergeldsystem kann optimiert werden, um Kosten zu sparen.',
        'is' => 'Zur Zeit erhalten die Eltern für jedes Kind ca. 250 Euro Kindergeld.',
        'problem' => 'Einige nutzen dieses System gezielt aus.',
        'gov' => 'Kindergeld soll wegen Inflation erhöht werden.',
        'error' => '',
        'we' => 'Das Kindergeld sollte gestaffelt reduziert werden. Für die erstgeborenen (evtl. Zwillinge) gibt es €300 pro Kind. Für den zweiten Schwung je 200. Für den 3. Kind/Schwung 100. Ab da nichts mehr.',
        'goal' => 'Damit sollen Kosten reduziert werden. Kleidung kann aufgetragen werden, Nahrungsmittelversorgung sollte ebenfalls passen.',
        'disc' => [
        ],
        'voting' => '0',
        'petition' => null,
    ],

    '48' => [
        'country' => 'DE',
        'topic' => 'Religion',
        'descr' => 'Ausüben der Religion in der Öffentlichkeit führt zu Spannungen.',
        'is' => 'Es gibt Religionsfreiheit und eine hohe Toleranz.',
        'problem' => 'Dies schüchtert ein und führt zu Mißverständnissen.',
        'gov' => '',
        'error' => '',
        'we' => 'Ausübung von Religion in der Öffentlichkeit verbieten. Hohe Strafen einführen. Auch Fische auf dem Auto sind verboten.',
        'goal' => 'Relativierung der Religionen. Leichterer Kontakt der unterschiedlichen Menschen.',
        'disc' => [
        ],
        'voting' => '0',
        'petition' => null,
    ],

    '49' => [
        'country' => 'UK',
        'topic' => 'Julian Assange',
        'descr' => 'Wir unterstützen die Befreiung von Julian Assange. Informiert euch auf https://www.actvism.org/ und https://writejulian.com/',
        'is' => '',
        'problem' => '',
        'gov' => '',
        'error' => '',
        'we' => 'Ausübung von Religion in der Öffentlichkeit verbieten. Hohe Strafen einführen. Auch Fische auf dem Auto sind verboten.',
        'goal' => 'Relativierung der Religionen. Leichterer Kontakt der unterschiedlichen Menschen.',
        'disc' => [
        ],
        'voting' => '0',
        'petition' => null,
    ],
];
